name: tests
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.targets.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Create matrix from bake file
        id: targets
        run: |
          echo 'matrix<<EOF' >> $GITHUB_OUTPUT
          docker buildx bake extract-test-targets; cat build/extract-test-targets/test-targets >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      -
        name: Show matrix
        run: |
          echo '${{ steps.targets.outputs.matrix }}'
  run_target:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs:
      - setup-matrix
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      -
        name: Run tests
        uses: docker/bake-action@v2
        with:
          targets: ${{ matrix.target }}
          set: |
            *.cache-from=type=gha,scope=test-v1-${{ matrix.target }}
            *.cache-to=type=gha,mode=max,scope=test-v1-${{ matrix.target }}
          